// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neytvmfumtpctlumwefg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5leXR2bWZ1bXRwY3RsdW13ZWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzU4MTksImV4cCI6MjA2NTgxMTgxOX0.Swktu5qTa_8hzKfavlynK7uZUny-OBFCIh6OkgyT6UM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);